import type { Metadata } from 'next';
import './globals.css';
import { Footer, NavbarMain } from '../components';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" dir="rtl">
			<body className={`antialiased`}>
				<NavbarMain />
				{children}
				<Footer />
			</body>
		</html>
	);
}
